name: Push Backend Container to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set_env-and-push-container:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: |
        echo "DB_HOST=${{secrets.DB_HOST}} \
        DB_ID=${{secrets.DB_ID}} \
        DB_PASS=${{secrets.DB_PASSWD}} \
        DB_PORT=${{secrets.DB_PORT}} \
        DATABASE=${{secrets.DB_NAME}} \
        PROJECT_ROOT=<dynamic> \
        PORT=${{secrets.BACKEND_PORT}} \
        CORS_URL=${{secrets.CORS_URL}} \
        CDN_URL=${{secrets.CDN_URL}}" > .env
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}
    - name: AWS ECR Login
      run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT}}
    - name: Push Container
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t ${{secrets.AWS_ACCOUNT}}/community:backend .
