name: Push Backend Container to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set_env-and-push-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set env
      run: |
        echo "DB_HOST=${{secrets.DB_HOST}}" > .env
        echo "DB_ID=${{secrets.DB_ID}}" >> .env
        echo "DB_PASS=${{secrets.DB_PASSWD}}" >> .env
        echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
        echo "DATABASE=${{secrets.DB_NAME}}" >> .env
        echo "PROJECT_ROOT=<dynamic>" >> .env
        echo "PORT=${{secrets.BACKEND_PORT}}" >> .env
        echo "CORS_URL=${{secrets.CORS_URL}}" >> .env
        echo "CDN_URL=${{secrets.CDN_URL}}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> .env
        echo "AWS_REGION=${{secrets.AWS_REGION}}" >> .env
        echo "AWS_S3_BUCKET_NAME=${{secrets.AWS_S3_BUCKET_NAME}}" >> .env
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}
    - name: AWS ECR Login
      run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT}}
    - name: Push Container
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t ${{secrets.AWS_ACCOUNT}}/community:backend .
